(() => {
const translations = {
"Kiana Curated Living Salon Dubai":"مساحة معيشة مختارة من كيانا في دبي","Art wall decor":"لوحات فنية للحائط","Art Works & Canvas Murals":"أعمال فنية ولوحات قماشية","Sculptural Decor Objects":"قطع ديكور نحتية","Designer Lighting & Lamps":"مصابيح وإضاءة بتصاميم مميزة","Cushions & Living Textiles":"وسائد ومنسوجات للمنزل","Outdoor Patio & Balcony Furniture":"أثاث الفناء والشرفة","Curved Boucle Sofa in Luxury Dubai Villa":"أريكة بوكليه منحنية في فيلا فاخرة بدبي","Modern Architectural Homes":"منازل بتصاميم معمارية حديثة","Green interior design inspiration":"إلهام للتصميم الداخلي الأخضر","Reinterpreting the classic bookshelf":"تصور جديد لرف الكتب الكلاسيكي","Instagram Atelier":"كيانا على إنستغرام","Facebook Atelier":"كيانا على فيسبوك","Direct WhatsApp Channel":"تواصل مباشر عبر واتساب",
"KIANA":"كيانا","HOME DÉCOR — DUBAI":"ديكور المنزل — دبي","KIANA HOME DÉCOR":"كيانا هوم ديكور","KIANA FURNITURE TRADING LLC":"كيانا لتجارة الأثاث ذ.م.م",
"Kiana Home Décor | Luxury Living & Atelier Furniture Dubai":"كيانا هوم ديكور | ديكور وأثاث فاخر في دبي",
"Complimentary Delivery Across UAE":"توصيل مجاني إلى جميع أنحاء الإمارات",
"Kiana Home Decor · Dubai":"كيانا هوم ديكور · دبي",
"WhatsApp: +971 50 9407 385":"واتساب: ‎+971 50 9407 385",
"Delivery Across UAE | WhatsApp: +971 50 9407 385":"توصيل داخل الإمارات | واتساب: ‎+971 50 9407 385",
"AED (United Arab Emirates)":"درهم إماراتي (الإمارات العربية المتحدة)","Concierge Desk":"خدمة العملاء",
"Curated Collections":"تشكيلات مختارة","Art Works & Wall Art":"الأعمال الفنية ولوحات الحائط","Mirrors":"المرايا","Designer Lighting":"إضاءة بتصاميم مميزة","Living & Cushions":"إكسسوارات المعيشة والوسائد","Outdoor Living":"المساحات الخارجية","Atelier Journal":"مجلة كيانا","0 Items • 0.00 AED":"٠ منتجات • ٠٫٠٠ د.إ",
"The Dubai Edit • 2026 Atelier Collection":"مختارات دبي • تشكيلة ٢٠٢٦","KIANA ARCHIVES":"أرشيف كيانا","Artful Living,":"حياة يزيّنها الفن،","Curated":"مختارات بعناية","for Extraordinary Spaces.":"لمساحات استثنائية.",
"Transform your home into a haven of warmth, sculptural charm, and timeless elegance. Handpicked from master artisans worldwide, delivered with care across the UAE.":"حوّل منزلك إلى ملاذ من الدفء والجمال والأناقة الخالدة. قطع منتقاة بعناية من إبداعات الحرفيين حول العالم، تصلك بكل عناية إلى جميع أنحاء الإمارات.",
"Explore New Arrivals":"اكتشف أحدث المنتجات","Book Consultation":"احجز استشارة","Delivery":"التوصيل","Complimentary UAE":"مجاني داخل الإمارات","Quality":"الجودة","Artisanal & Handcrafted":"حِرفية وصناعة يدوية","Assistance":"المساعدة","Dubai Customer Care":"خدمة العملاء في دبي","The Kiana Living Edit":"مختارات كيانا للمنزل","The Art of Everyday Living":"فن الحياة اليومية","Collection 2026":"تشكيلة ٢٠٢٦","Trending Art":"أحدث الأعمال الفنية","Discover Wall Art":"اكتشف لوحات الحائط","View Wall Series →":"استعرض مجموعة اللوحات ←","EXPLORE OUR ATELIER":"اكتشف عالم كيانا","Curated Living Disciplines":"تشكيلات مختارة لكل مساحة",
"Meticulously selected collections to elevate every corner of your residence, from private villas in Emirates Hills to urban high-rises in Downtown Dubai.":"تشكيلات منتقاة بعناية لترتقي بكل ركن في منزلك، من الفلل الخاصة في تلال الإمارات إلى الشقق العصرية في وسط دبي.",
"25 Pieces":"٢٥ قطعة","Reflections":"انعكاسات","Architectural Mirrors":"مرايا بتصاميم معمارية","Organic branch motifs, brass arches, and sculpted statement wall mirrors.":"مرايا حائط مميزة بتفاصيل الأغصان الطبيعية والأقواس النحاسية والتشكيلات النحتية.","150+ Pieces":"أكثر من ١٥٠ قطعة","Wall Fine Art":"فنون الحائط","Abstract Art & Diptychs":"فن تجريدي ولوحات ثنائية","Geometric compositions, gold foil prints, and framed canvas duos for gallery walls.":"تكوينات هندسية وطبعات بورق الذهب ولوحات قماشية ثنائية مؤطرة لجدران تنبض بالفن.","70 Pieces":"٧٠ قطعة","Objects d'Art":"تحف فنية","Sculptural Accents & Knot Décor":"مجسمات فنية وديكورات العُقد","Monochrome stoneware, interlocking arches, and tactile coffee table centerpieces.":"خزفيات أحادية اللون وأقواس متداخلة وقطع مميزة لطاولات القهوة.","24 Designs":"٢٤ تصميماً","Illumination":"عالم الإضاءة","Designer Lamps & Floor Stands":"مصابيح مميزة وإضاءة أرضية","Travertine cylinders, linen shade table lamps, and geometric architectural tripods.":"تصاميم أسطوانية من الترافرتين ومصابيح طاولة بظلال كتانية وقواعد ثلاثية هندسية.","New In":"وصل حديثاً","Soft Living":"لمسات ناعمة","Plush Cushions & Linen Accents":"وسائد ناعمة ولمسات كتانية","Geometric velvet, woven bouclé, and desert neutral tones engineered for comfort.":"مخمل بنقوش هندسية وبوكليه منسوج وألوان صحراوية هادئة تمنحك الراحة.","Garden & Terrace":"الحديقة والشرفة","Outdoor Furniture Sets":"أطقم الأثاث الخارجي","Weatherproof woven rope bistro sets and minimalist terrace seating for UAE winters.":"أطقم من الحبال المنسوجة مقاومة للعوامل الجوية وجلسات بسيطة للشرفات، مثالية لشتاء الإمارات.",
"CURATED CATALOGUE":"كتالوج مختار بعناية","Signature Acquisitions":"قطع مميزة لمنزلك","Each piece in our collection is handpicked for its exceptional craft, timeless appeal, and expressive aesthetic.":"نختار كل قطعة في تشكيلتنا لحرفيتها الاستثنائية وجمالها الدائم وشخصيتها الفنية المميزة.","All Featured":"جميع المختارات","Art Works":"الأعمال الفنية","Lights & Furniture":"الإضاءة والأثاث","Mirrors & Accents":"المرايا والإكسسوارات","Furniture":"الأثاث","Lighting":"الإضاءة","Lights":"الإضاءة","Décor":"الديكور","Decor":"الديكور",
"2 Seater Outdoor Patio Set":"طقم جلسة خارجية لشخصين","Abstract Framed Wall Art":"لوحة تجريدية مؤطرة","Valora Table Lamp":"مصباح طاولة فالورا","Silhouette Framed Mirror":"مرآة سيلويت مؤطرة","Decorative Monstera Leaf Sculpture":"مجسم ورقة مونستيرا للزينة","Decorative Floral Glass Vase Set":"طقم مزهريات زجاجية بالزهور","Bellora Dome Table Lamp":"مصباح طاولة بيلورا بقبة","Riviera Wave Framed Mirror":"مرآة ريفييرا ويف مؤطرة","Decorative Glass Mushroom":"قطعة زينة زجاجية بشكل فطر","Gold Arc Table Lamp":"مصباح طاولة بقوس ذهبي","Silver Linear Opulence Frame Grid Framed Mirror":"مرآة مؤطرة بتصميم شبكي فضي","Snoopy Metallica Pop Art Frame":"لوحة بوب آرت سنوبي ميتاليكا",
"Bring contemporary elegance to your outdoor space with this stylish 3-piece bistro set, featuring two woven rope armchairs and a matching dining table.":"أضف أناقة عصرية لمساحتك الخارجية مع هذا الطقم المكوّن من ثلاث قطع: كرسيان من الحبال المنسوجة وطاولة طعام متناسقة.","Bring a touch of sophistication and creativity to your home, office, or any space with abstract wall art that combines timeless design with modern elegance.":"امنح منزلك أو مكتبك لمسة من الرقي والإبداع بلوحة تجريدية تجمع بين التصميم الخالد والأناقة العصرية.","Elevate your interior with the Valora Table Lamp , a stunning blend of sculptural design and contemporary elegance.":"ارتقِ بديكورك مع مصباح طاولة فالورا الذي يجمع بين التصميم النحتي والأناقة العصرية.","Make a bold artistic statement with The Silhouette Mirror, a contemporary wall accent that combines sculptural design with functional elegance.":"أضف لمسة فنية لافتة مع مرآة سيلويت، قطعة حائط عصرية تجمع بين التصميم النحتي والأناقة العملية.","Celebrate the beauty of nature with the timeless elegance of the Decorative Monstera Leaf Sculpture .":"احتفِ بجمال الطبيعة والأناقة الدائمة مع مجسم ورقة المونستيرا للزينة.","Add a touch of timeless elegance to your home with the Floral Glass Vase Set — a beautifully crafted collection of three round glass vases featuring real pressed flowers preserved within clear premium glass.":"أضف لمسة من الأناقة إلى منزلك مع طقم من ثلاث مزهريات زجاجية مستديرة، تضم زهوراً طبيعية مضغوطة محفوظة داخل زجاج شفاف عالي الجودة.","The Bellora Dome Table Lamp is a sophisticated blend of modern elegance and natural warmth.":"يجمع مصباح طاولة بيلورا بين الأناقة العصرية والدفء الطبيعي.","Make a bold artistic statement with the Riviera Wave Mirror, a captivating design inspired by the fluid beauty of ocean waves and organic movement.":"أضف لمسة فنية لافتة مع مرآة ريفييرا ويف، بتصميم آسر مستوحى من انسيابية أمواج البحر والحركة الطبيعية.",
"View Complete Collection":"استعرض التشكيلة كاملة","Spotlight Piece":"قطعة تحت الأضواء","ARCHITECTURAL ILLUMINATION":"إضاءة بطابع معماري","Contemporary Black Metal Tripod Floor Lamp":"مصباح أرضي عصري أسود بقاعدة معدنية ثلاثية","A geometric sculptural centerpiece engineered with architectural proportions. Its multifaceted drum shade diffuses a warm ambient glow, perfect for anchoring intimate reading corners and expansive open-plan Dubai salons.":"قطعة هندسية لافتة بنسب معمارية متوازنة. يوزع غطاؤها متعدد الأوجه إضاءة دافئة وهادئة، لتناسب زوايا القراءة المريحة وصالات دبي الواسعة.","Available from Kiana Home Decor":"متوفر لدى كيانا هوم ديكور","Add To Cart":"أضف إلى السلة","Explore Lighting":"اكتشف الإضاءة","Inquire on WhatsApp":"استفسر عبر واتساب","E27 Warm LED Compatible":"متوافق مع لمبات LED دافئة بقاعدة E27","Matte Anti-Glare Finish":"سطح مطفأ يقلل الوهج","DUBAI STUDIO":"استوديو دبي","“Every room is an opportunity for creative expression.”":"«كل غرفة فرصة للتعبير الإبداعي.»","ABOUT OUR STORE":"عن متجرنا","Buy Designer Home Décor Accessories Online in Dubai & UAE.":"تسوّق إكسسوارات منزلية بتصاميم مميزة في دبي والإمارات.",
"Our home shows the world who we are. How we decorate our home offers a glimpse into our unique personality, taste, and style. The right home accessories—like cushions, lamps, rugs, objects d’art, mirrors, and curtains—can take your living space to another level. These add layers to a room, essentially completing and pulling together the way it looks and feels.":"يعكس منزلنا شخصيتنا وذوقنا وأسلوبنا الخاص. ويمكن للإكسسوارات المناسبة، كالوسائد والمصابيح والسجاد والتحف والمرايا والستائر، أن ترتقي بمساحة المعيشة وتمنحها عمقاً وتناسقاً يكتمل به جمالها وإحساسها.","Welcome to":"مرحباً بكم في","Kiana Home Décor,":"كيانا هوم ديكور،","your premier online shopping destination for innovative modern home accessories at exceptional value. Indulge in the art of home styling with our diverse range of products, meticulously sourced from artisans and designers around the globe.":"وجهتكم للتسوق الإلكتروني لإكسسوارات منزلية عصرية ومبتكرة بقيمة مميزة. اكتشفوا فن تنسيق المنزل مع منتجات متنوعة نختارها بعناية من حرفيين ومصممين حول العالم.","Whether you are drawn to the rustic allure of farmhouse chic, the sleek lines of modern minimalism, or the opulent elegance of classic Arabian glamour, our atelier delivers seamless white-glove satisfaction from inspiration to installation.":"سواء كنتم تفضلون سحر الطابع الريفي أو بساطة الخطوط العصرية أو فخامة الأناقة العربية الكلاسيكية، نرافقكم بعناية من الإلهام حتى اكتمال مساحتكم.","White-Glove":"توصيل بعناية فائقة","Careful room placement across all 7 Emirates.":"وضع القطع بعناية داخل المنزل في الإمارات السبع.","Authentic Quality":"جودة أصيلة","Handcrafted finishes and archival canvases.":"تشطيبات حرفية ولوحات قماشية عالية الجودة.","Atelier Styling":"تنسيق الديكور","Direct stylist consultation via WhatsApp.":"استشارة مباشرة لتنسيق الديكور عبر واتساب.","Connect With A Stylist":"تواصل مع مستشار الديكور",
"FURNITURE GUIDES & JOURNAL":"دليل الأثاث ومجلة كيانا","Our Latest Perspectives":"أحدث أفكارنا وإلهاماتنا","Read All Journal Entries":"اقرأ جميع المقالات","Decoration":"الديكور","27 AUG 2024 • ATELIER ESSAY":"٢٧ أغسطس ٢٠٢٤ • مقال كيانا","Exploring Atlanta & Dubai’s Modern Architectural Homes":"استكشاف المنازل المعمارية الحديثة في أتلانتا ودبي","How contemporary residential planning merges generous natural limestone lightwells with understated sculptural statement furnishings.":"كيف تجمع التصاميم السكنية المعاصرة بين فتحات الإضاءة الرحبة من الحجر الجيري الطبيعي والأثاث النحتي الأنيق.","Continue Reading":"تابع القراءة","Inspiration":"إلهام","27 AUG 2024 • BOTANICAL LIVING":"٢٧ أغسطس ٢٠٢٤ • حياة مستوحاة من الطبيعة","Green Interior Design & Biophilic Accents in the Emirates":"التصميم الداخلي الأخضر ولمسات الطبيعة في الإمارات","Selecting earthen pigments, botanical diptychs, and natural woven materials to foster a calm sanctuary from the vibrant city pulse.":"اختيار الألوان الترابية واللوحات النباتية الثنائية والخامات الطبيعية المنسوجة لصنع ملاذ هادئ بعيداً عن صخب المدينة.","Design Trends":"اتجاهات التصميم","27 AUG 2024 • STYLING RITUALS":"٢٧ أغسطس ٢٠٢٤ • فن التنسيق","The Curated Bookshelf & Ceramic Objects d'Art":"تنسيق رفوف الكتب والتحف الخزفية","Mastering the balance between monochrome stoneware knots, framed miniature prints, and warm lighting layers on open shelving.":"إتقان التوازن بين التحف الخزفية أحادية اللون واللوحات الصغيرة المؤطرة وطبقات الإضاءة الدافئة على الرفوف المفتوحة.",
"BESPOKE INTERIOR SOURCING":"اختيارات خاصة لديكور منزلك","Let’s Find the Finishing Touches for Your Home.":"لنجد معاً اللمسات التي تُكمل جمال منزلك.","Connect with Kiana’s Dubai team to explore wall art, statement mirrors, lighting and decorative accessories for your space.":"تواصل مع فريق كيانا في دبي لاكتشاف لوحات الحائط والمرايا المميزة والإضاءة وإكسسوارات الديكور المناسبة لمساحتك.","WhatsApp Concierge":"خدمة العملاء عبر واتساب","Email Dubai Atelier":"راسل فريق دبي","Curators of distinctive living accessories, bespoke art pieces, and artisanal furniture in the heart of Dubai, UAE. Bringing timeless European craftsmanship and Arabian architectural grandeur to discerning residences.":"نختار إكسسوارات منزلية مميزة وقطعاً فنية وأثاثاً حرفياً في قلب دبي، لنمنح المنازل لمسات تجمع بين الحرفية الأوروبية وجمال العمارة العربية.","WhatsApp Concierge: +971 50 9407 385":"خدمة العملاء عبر واتساب: ‎+971 50 9407 385",
"Curated Categories":"فئات مختارة","Pop Art & Abstract Prints":"فن البوب والطبعات التجريدية","Architectural Heritage Mirrors":"مرايا بطابع معماري تراثي","Sculptural Stone & Bronze Décor":"ديكورات نحتية من الحجر والبرونز","Designer Lamps & Crystal Lighting":"مصابيح مميزة وإضاءة كريستالية","Bespoke Velvet & Linen Cushions":"وسائد مخملية وكتانية مميزة","Outdoor Teak & Travertine Patio Sets":"أطقم خارجية من خشب الساج والترافرتين","Client Care & Services":"خدمة العملاء والخدمات","Dubai White-Glove Delivery":"توصيل بعناية فائقة في دبي","Bespoke Interior Curation":"تنسيق داخلي حسب الطلب","Methods of Payment":"طرق الدفع","Return & Exchange Policy":"سياسة الإرجاع والاستبدال","Privacy Policy":"سياسة الخصوصية","Terms & Conditions":"الشروط والأحكام","Dubai Studio & Inquiries":"استوديو دبي والاستفسارات","Kiana Furniture Trading LLC":"كيانا لتجارة الأثاث ذ.م.م","Dubai, United Arab Emirates":"دبي، الإمارات العربية المتحدة","Contact our team for assistance":"تواصل مع فريقنا للمساعدة","Private Catalogue Access":"احصل على الكتالوج","© 2026 Kiana Home Décor. All rights reserved. Registered with Kiana Furniture Trading LLC.":"© ٢٠٢٦ كيانا هوم ديكور. جميع الحقوق محفوظة. مسجلة باسم كيانا لتجارة الأثاث ذ.م.م.","Secure Encrypted Checkout in AED":"دفع آمن ومشفّر بالدرهم الإماراتي","Visa, Mastercard & Wire Transfers":"فيزا وماستركارد والتحويلات البنكية",
"Client design preview · Styling follows the supplied concept; the catalogue uses Kiana product information. Confirm product specifications, prices and availability with Kiana’s official store.":"معاينة التصميم للعميل · التنسيق مستوحى من التصميم المقدم، والكتالوج يعرض معلومات منتجات كيانا. يُرجى تأكيد المواصفات والأسعار والتوفر لدى متجر كيانا الرسمي.","Client design preview · Featured styling follows the supplied concept. Confirm product specifications, prices and availability with Kiana’s official store.":"معاينة التصميم للعميل · التنسيق مستوحى من التصميم المقدم. يُرجى تأكيد مواصفات المنتجات والأسعار والتوفر لدى متجر كيانا الرسمي.",
"Home":"الرئيسية","/ Curated Collections":"/ تشكيلات مختارة","THE KIANA ATELIER":"عالم كيانا","Objects of Everyday Beauty.":"قطع تضفي الجمال على كل يوم.","Discover the art, lighting and finishing touches that make a space your own.":"اكتشف الفن والإضاءة واللمسات الأخيرة التي تجعل مساحتك تعبّر عنك.","All Pieces":"جميع القطع","Sort by":"ترتيب حسب","Featured":"مختاراتنا","Price: low to high":"السعر: من الأقل إلى الأعلى","Price: high to low":"السعر: من الأعلى إلى الأقل","Name: A–Z":"الاسم: أبجدياً",
"Your Curated Wishlist":"قائمة أمنياتك المختارة","Save pieces using the heart beside each product.":"احفظ القطع بالضغط على رمز القلب بجانب كل منتج.","Explore the collection":"استكشف التشكيلة","Search the Collection":"ابحث في التشكيلة","Find a piece for your home":"اعثر على قطعة لمنزلك","Try lamps, mirrors or art":"جرّب المصابيح أو المرايا أو الفن","Search":"بحث","All Collections":"جميع التشكيلات","Contact":"تواصل معنا","Explore related pieces":"استكشف قطعاً مشابهة","Your email address":"بريدك الإلكتروني","No matching pieces. Try another search or category.":"لا توجد قطع مطابقة. جرّب بحثاً أو فئة أخرى.","Unable to load the catalogue.":"تعذر تحميل الكتالوج.","Visit the official store":"زيارة المتجر الرسمي",
"Search Catalogue":"البحث في الكتالوج","Curated Wishlist":"قائمة الأمنيات","Account and Concierge":"الحساب وخدمة العملاء","Toggle Mobile Menu":"فتح أو إغلاق القائمة","Add to Wishlist":"أضف إلى قائمة الأمنيات","Close dialog":"إغلاق النافذة","Request catalogue by email":"طلب الكتالوج عبر البريد الإلكتروني"
};
const normalize=s=>s.trim().replace(/\s+/g,' ');
const translate=s=>{
 const key=normalize(s);if(translations[key])return translations[key];
 if(/^AED\s+[\d,.]+$/.test(key))return key.replace('AED','د.إ');
 if(/^[\d,.]+\s+AED(?: Set)?$/.test(key))return key.replace('AED','د.إ').replace('Set','للطقم');
 const count=key.match(/^(\d+) curated pieces(?: matching “(.*)”)?? · Prices shown in AED$/);
 if(count)return `${count[1]} قطعة مختارة${count[2]?' تطابق «'+count[2]+'»':''} · الأسعار بالدرهم الإماراتي`;
 for(const [prefix,ar] of [['Save ','احفظ '],['Explore ','اكتشف '],['View ','عرض ']])if(key.startsWith(prefix)){const name=key.slice(prefix.length).replace(/ at Kiana$/,'');return ar+(translations[name]||name);}
 return s;
};
window.kianaTranslate=translate;
let language='en';try{language=localStorage.getItem('kiana-language')==='ar'?'ar':'en'}catch{}
const textOriginals=new WeakMap(),attributeOriginals=new WeakMap();
const button=document.getElementById('language-toggle');
const observer=new MutationObserver(()=>apply());
function apply(){
 observer.disconnect();document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';
 const walker=document.createTreeWalker(document.documentElement,NodeFilter.SHOW_TEXT);
 let node;while(node=walker.nextNode()){
  if(!node.parentElement||node.parentElement.closest('script,style,.material-symbols-outlined,#language-toggle,[data-no-translate]'))continue;
  let record=textOriginals.get(node);if(!record||node.nodeValue!==record.last)record={original:node.nodeValue};
  record.last=language==='ar'?record.original.replace(/\S[\s\S]*\S|\S/,value=>translate(value)):record.original;node.nodeValue=record.last;textOriginals.set(node,record);
 }
 document.querySelectorAll('[placeholder],[alt],[aria-label]').forEach(el=>{if(el===button||el.closest('[data-no-translate]'))return;let records=attributeOriginals.get(el)||{};for(const name of ['placeholder','alt','aria-label']){if(!el.hasAttribute(name))continue;let record=records[name];const current=el.getAttribute(name);if(!record||current!==record.last)record={original:current};record.last=language==='ar'?translate(record.original):record.original;el.setAttribute(name,record.last);records[name]=record;}attributeOriginals.set(el,records);});
 button.textContent=language==='ar'?'EN':'العربية';button.lang=language==='ar'?'en':'ar';button.setAttribute('aria-label',language==='ar'?'Switch to English':'التبديل إلى العربية');
 observer.observe(document.body,{childList:true,subtree:true,characterData:true});
}
button.addEventListener('click',()=>{language=language==='en'?'ar':'en';try{localStorage.setItem('kiana-language',language)}catch{}apply();if(typeof render==='function'){render();apply();}});
apply();
})();

