const dialog=document.getElementById('k-dialog');
const params=new URLSearchParams(location.search);let category=params.get('category')||'All Pieces',query=params.get('search')||'',sort='featured';let catalogue=[];let saved=[];try{saved=JSON.parse(localStorage.getItem('kiana-saved')||'[]')}catch{}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(content){dialog.innerHTML='<button class="close" aria-label="Close dialog">×</button>'+content;dialog.querySelector('.close').onclick=()=>dialog.close();dialog.showModal();}
dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
function wishlist(){show('<h2>Your Curated Wishlist</h2>'+(saved.length?'<ul>'+saved.map(n=>'<li style="padding:12px 0;border-bottom:1px solid #ddd">'+escapeHTML(n)+'</li>').join('')+'</ul>':'<p>Save pieces using the heart beside each product.</p>')+'<a class="action" href="./collections.html">Explore the collection</a>');}
function updateSaved(){document.querySelectorAll('[data-path="wishlist"] span:last-child').forEach(el=>el.textContent=saved.length);document.querySelectorAll('[data-save]').forEach(b=>{const yes=saved.includes(b.dataset.save);b.classList.toggle('wishlist-on',yes);b.setAttribute('aria-pressed',yes);b.onclick=()=>{const n=b.dataset.save;saved=saved.includes(n)?saved.filter(x=>x!==n):[...saved,n];try{localStorage.setItem('kiana-saved',JSON.stringify(saved))}catch{}updateSaved();};});}
const categoryLink=c=>'./collections.html?category='+encodeURIComponent(c);
const paths={'home':'./','curated-collections':'./collections.html','art-works':categoryLink('Art Works'),'mirrors':categoryLink('Mirrors'),'designer-lighting':categoryLink('Lighting'),'living-and-cushions':'https://www.kianahomedecor.com/product-category/cushions/','outdoor-living':categoryLink('Furniture'),'atelier-journal':'./#journal','client-inquiries':'./#contact','client-portal':'./#contact','shopping-bag':'https://www.kianahomedecor.com/cart/','white-glove-delivery':'./#contact','interior-curation':'./#contact','payment-methods':'https://www.kianahomedecor.com/','returns-policy':'https://www.kianahomedecor.com/','privacy-policy':'https://www.kianahomedecor.com/','terms-conditions':'https://www.kianahomedecor.com/'};
document.querySelectorAll('[data-path]').forEach(a=>{if(a.dataset.path==='wishlist'){a.href='#wishlist';a.onclick=e=>{e.preventDefault();wishlist();};}else a.href=paths[a.dataset.path]||'./collections.html';});
document.querySelectorAll('button[aria-label="Search Catalogue"]').forEach(b=>b.onclick=()=>{show('<h2>Search the Collection</h2><form id="search"><label for="query">Find a piece for your home</label><input id="query" name="search" placeholder="Try lamps, mirrors or art" autocomplete="off"><button class="action" type="submit">Search</button></form>');dialog.querySelector('form').onsubmit=e=>{e.preventDefault();location.href='./collections.html?search='+encodeURIComponent(dialog.querySelector('input').value);};dialog.querySelector('input').focus();});
document.querySelectorAll('button[aria-label="Toggle Mobile Menu"]').forEach(b=>{b.dataset.mobileToggle='true';b.setAttribute('aria-expanded','false');b.onclick=()=>{let menu=document.getElementById('mobile-links');if(!menu){menu=document.createElement('nav');menu.id='mobile-links';menu.className='mobile-links';menu.innerHTML=Object.entries({'All Collections':'./collections.html','Art Works':categoryLink('Art Works'),'Mirrors':categoryLink('Mirrors'),'Lighting':categoryLink('Lighting'),'Outdoor Living':categoryLink('Furniture'),'Contact':'./#contact'}).map(([n,h])=>`<a href="${h}">${n}</a>`).join('');document.querySelector('header').append(menu);}else menu.hidden=!menu.hidden;b.setAttribute('aria-expanded',!menu.hidden);};});
document.querySelectorAll('#categories a.group').forEach((a,i)=>a.href=[categoryLink('Mirrors'),categoryLink('Art Works'),categoryLink('Décor'),categoryLink('Lighting'),'https://www.kianahomedecor.com/product-category/cushions/',categoryLink('Furniture')][i]);
document.querySelectorAll('#featured-products .group.flex.flex-col').forEach(card=>{const name=card.querySelector('h4').textContent.trim();card.dataset.type=card.querySelector('.p-5 .font-label-uppercase').textContent.trim();card.querySelectorAll('button').forEach(b=>{if(b.getAttribute('aria-label')==='Add to Wishlist'){b.dataset.save=name;}else{b.setAttribute('aria-label','Explore '+name);b.innerHTML='<span class="material-symbols-outlined text-[18px]">arrow_outward</span>';b.onclick=()=>location.href=categoryLink(card.dataset.type==='Lights'?'Lighting':card.dataset.type==='Decor'?'Décor':card.dataset.type==='Outdoor Living'?'Furniture':card.dataset.type);}});});
document.querySelectorAll('#featured-products .flex.flex-wrap button').forEach(b=>{b.dataset.label=b.textContent.trim();b.onclick=()=>{const label=b.dataset.label;document.querySelectorAll('#featured-products .flex.flex-wrap button').forEach(x=>{x.classList.toggle('active-filter',x===b);x.classList.remove('bg-obsidian-ink','text-surface-container-lowest');x.setAttribute('aria-pressed',x===b);});document.querySelectorAll('#featured-products .group.flex.flex-col').forEach(card=>card.hidden=label!=='All Featured'&&!(label==='Art Works'?card.dataset.type==='Art Works':label==='Lights & Furniture'?['Lights','Lighting','Furniture','Outdoor Living'].includes(card.dataset.type):['Mirrors','Decor','Décor'].includes(card.dataset.type)));};});
document.querySelectorAll('a[href="#"]').forEach(a=>{const t=a.textContent.trim();a.href=/Journal|Entries/.test(t)?'./#journal':/Stylist|Care|Contact/.test(t)?'./#contact':'./collections.html';});
document.querySelectorAll('button').forEach(b=>{if(b.textContent.trim()==='Add To Cart'){b.textContent='Explore Lighting';b.onclick=()=>location.href=categoryLink('Lighting');}});
document.querySelectorAll('#journal article').forEach(a=>{a.tabIndex=0;a.setAttribute('role','button');a.style.cursor='pointer';const journalTitle=a.querySelector('h3').textContent,journalText=a.querySelector('p').textContent;const open=()=>show('<h2>'+journalTitle+'</h2><p>'+journalText+'</p><a class="action" href="./collections.html">Explore related pieces</a>');a.onclick=open;a.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}};});
const email=document.querySelector('footer input[type="email"]');if(email){const b=email.nextElementSibling;b.setAttribute('aria-label','Request catalogue by email');b.onclick=()=>{if(!email.reportValidity()||!email.value)return;location.href='mailto:sales@kianahomedecor.com?subject=Kiana%20Catalogue%20Request&body='+encodeURIComponent('Please send your catalogue to '+email.value);};}
function render(){const grid=document.getElementById('catalog-grid');if(!grid)return;let items=catalogue.filter(p=>(category==='All Pieces'||p.category===category)&&(`${p.name} ${p.category} ${window.kianaTranslate?window.kianaTranslate(p.name)+' '+window.kianaTranslate(p.category):''}`).toLowerCase().includes(query.toLowerCase()));if(sort==='name')items.sort((a,b)=>(document.documentElement.lang==='ar'&&window.kianaTranslate?window.kianaTranslate(a.name).localeCompare(window.kianaTranslate(b.name),'ar'):a.name.localeCompare(b.name)));if(sort.startsWith('price'))items.sort((a,b)=>(a.price-b.price)*(sort==='price-asc'?1:-1));grid.innerHTML=items.map(p=>`<article class="catalog-card"><div class="relative"><a href="${p.url}" target="_blank" rel="noopener"><img src=".${p.image}" alt="${escapeHTML(p.name)}" loading="lazy"></a><button class="absolute top-3 right-3" data-save="${escapeHTML(p.name)}" aria-label="Save ${escapeHTML(p.name)}"><span class="material-symbols-outlined">favorite</span></button></div><div class="info"><p class="meta">${p.category}</p><h3><a href="${p.url}" target="_blank" rel="noopener">${p.name}</a></h3><div class="flex items-center justify-between"><p class="price">${p.detail}</p><a href="${p.url}" target="_blank" rel="noopener" aria-label="View ${escapeHTML(p.name)} at Kiana"><span class="material-symbols-outlined">arrow_outward</span></a></div></div></article>`).join('');if(!items.length)grid.innerHTML='<p>No matching pieces. Try another search or category.</p>';document.getElementById('catalog-count').textContent=`${items.length} curated pieces${query?' matching “'+query+'”':''} · Prices shown in AED`;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active-filter',b.dataset.filter===category);b.setAttribute('aria-pressed',b.dataset.filter===category);});updateSaved();}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{category=b.dataset.filter;const u=new URL(location.href);u.searchParams.set('category',category);history.replaceState({},'',u);render();});
const sortSelect=document.getElementById('catalog-sort');if(sortSelect)sortSelect.onchange=()=>{sort=sortSelect.value;render();};
if(document.getElementById('catalog-grid'))fetch('./products.json').then(r=>{if(!r.ok)throw Error('catalogue');return r.json()}).then(p=>{catalogue=p;render();}).catch(()=>{document.getElementById('catalog-count').innerHTML='Unable to load the catalogue. <a href="https://www.kianahomedecor.com/">Visit the official store</a>.';});
updateSaved();

